// DO NOT EDIT. Generated from tools/tui-abi/ui_abi.toml.
// schema_blake3 = aa92c1c46995f6daeab87f08ef493788c1b96ad6cb842a7322220675e9d1691e
// generator_blake3 = b24c4f5ded660a7363e3f0d9d7d248d155511bdaf4384d128827ac15e778f08d

#![allow(dead_code)]

pub const UI_ABI_NAME: &str = "iyon_tui_ui";
pub const UI_ABI_VERSION: u32 = 1;
pub const UI_SEMANTIC_SCHEMA_VERSION: u32 = 1;
pub const UI_MINIMUM_BUN: &str = "1.4.0";
pub const UI_QUALIFIED_BUN: &str = "1.4.0";
pub const UI_BATCH_MAGIC: u32 = 0x4959_5549;
pub const UI_BATCH_VERSION: u32 = 1;
pub const UI_BATCH_HEADER_WORDS: usize = 16;
pub const UI_ACK_HEADER_WORDS: usize = 8;
pub const UI_ACK_WORDS_PER_CREATED_HANDLE: usize = 4;
pub const UI_HANDLE_WORDS: usize = 4;
pub const UI_LOCAL_HANDLE_HOST: u32 = 0;
pub const UI_LOCAL_HANDLE_GENERATION: u32 = 0;
pub const UI_ACK_STATUS_ERROR_BIT: u32 = 0x8000_0000;
pub const UI_ACK_RESERVED: u32 = 0;

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum HostKind {
    Box = 1,
    ContentHost = 2,
    Editor = 3,
    Scroll = 4,
    Animation = 5,
}

impl HostKind {
    pub const fn from_code(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::Box),
            2 => Some(Self::ContentHost),
            3 => Some(Self::Editor),
            4 => Some(Self::Scroll),
            5 => Some(Self::Animation),
            _ => None,
        }
    }

    pub const fn code(self) -> u32 {
        self as u32
    }
}

impl HostKind {
    pub const fn accepts_children(self) -> bool {
        match self {
            Self::Box => true,
            Self::ContentHost => false,
            Self::Editor => false,
            Self::Scroll => true,
            Self::Animation => true,
        }
    }

    pub const fn child_cardinality(self) -> &'static str {
        match self {
            Self::Box => "many",
            Self::ContentHost => "none",
            Self::Editor => "none",
            Self::Scroll => "many",
            Self::Animation => "frames",
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ControlKind {
    Editor = 1,
    Scroll = 2,
    Animation = 3,
}

impl ControlKind {
    pub const fn from_code(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::Editor),
            2 => Some(Self::Scroll),
            3 => Some(Self::Animation),
            _ => None,
        }
    }

    pub const fn code(self) -> u32 {
        self as u32
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ControlCommandDescriptor {
    pub name: &'static str,
    pub code: u32,
    pub control_kind: ControlKind,
    pub operands: &'static [&'static str],
}

pub const CONTROL_COMMAND_DESCRIPTORS: &[ControlCommandDescriptor] = &[
    ControlCommandDescriptor {
        name: "EditorInsert",
        code: 1,
        control_kind: ControlKind::Editor,
        operands: &["codepoint_u32"],
    },
    ControlCommandDescriptor {
        name: "EditorSubmit",
        code: 2,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorInsertNewline",
        code: 3,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorBackspace",
        code: 4,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorDelete",
        code: 5,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorDeleteWordBackward",
        code: 6,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorDeleteWordForward",
        code: 7,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorKillToLineStart",
        code: 8,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorYank",
        code: 9,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveLeft",
        code: 10,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveRight",
        code: 11,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveWordLeft",
        code: 12,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveWordRight",
        code: 13,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveLineStart",
        code: 14,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveLineEnd",
        code: 15,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveUp",
        code: 16,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "EditorMoveDown",
        code: 17,
        control_kind: ControlKind::Editor,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "ScrollLineUp",
        code: 256,
        control_kind: ControlKind::Scroll,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "ScrollLineDown",
        code: 257,
        control_kind: ControlKind::Scroll,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "ScrollPageUp",
        code: 258,
        control_kind: ControlKind::Scroll,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "ScrollPageDown",
        code: 259,
        control_kind: ControlKind::Scroll,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "ScrollStart",
        code: 260,
        control_kind: ControlKind::Scroll,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "ScrollEnd",
        code: 261,
        control_kind: ControlKind::Scroll,
        operands: &[],
    },
    ControlCommandDescriptor {
        name: "AnimationStop",
        code: 512,
        control_kind: ControlKind::Animation,
        operands: &[],
    },
];

pub fn control_command_descriptor(code: u32) -> Option<&'static ControlCommandDescriptor> {
    CONTROL_COMMAND_DESCRIPTORS
        .iter()
        .find(|command| command.code == code)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UiConfigDescriptor {
    pub name: &'static str,
    pub owner: &'static str,
    pub kind: &'static str,
    pub value: &'static str,
}

pub const UI_CONFIG_DESCRIPTORS: &[UiConfigDescriptor] = &[
    UiConfigDescriptor {
        name: "EditorMultiline",
        owner: "control",
        kind: "Editor",
        value: "bool",
    },
    UiConfigDescriptor {
        name: "AnimationIntervalMs",
        owner: "control",
        kind: "Animation",
        value: "u32",
    },
    UiConfigDescriptor {
        name: "HistoryFlowBoundary",
        owner: "root",
        kind: "LegacyHistoryUnit",
        value: "flow_boundary",
    },
    UiConfigDescriptor {
        name: "HistoryUnitIdentity",
        owner: "root",
        kind: "LegacyHistoryUnit",
        value: "unit_identity",
    },
];

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum RootRole {
    Body = 1,
    Portal = 2,
    LegacyHistoryUnit = 3,
}

impl RootRole {
    pub const fn from_code(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::Body),
            2 => Some(Self::Portal),
            3 => Some(Self::LegacyHistoryUnit),
            _ => None,
        }
    }

    pub const fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum HandleKind {
    Node = 1,
    Port = 2,
    Connector = 3,
    Control = 4,
}

impl HandleKind {
    pub const fn from_code(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::Node),
            2 => Some(Self::Port),
            3 => Some(Self::Connector),
            4 => Some(Self::Control),
            _ => None,
        }
    }

    pub const fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum OwnershipMode {
    OccurrenceOwned = 1,
    Explicit = 2,
}

impl OwnershipMode {
    pub const fn from_code(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::OccurrenceOwned),
            2 => Some(Self::Explicit),
            _ => None,
        }
    }

    pub const fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ValueKind {
    U16 = 2,
    Insets = 3,
    Alignment = 4,
    Edges = 5,
    Color = 6,
    BorderStyle = 7,
    Glyphs = 8,
    TextAttributes = 9,
    Style = 10,
    LayoutMode = 11,
    Dimension = 12,
    F32 = 13,
    Display = 14,
    Direction = 15,
    FlexDirection = 16,
    FlexWrap = 17,
    Position = 18,
    AlignmentMode = 19,
    GridAutoFlow = 20,
    InsetsF32 = 21,
    TrackList = 22,
    GridPlacement = 23,
}

impl ValueKind {
    pub const fn from_code(value: u32) -> Option<Self> {
        match value {
            2 => Some(Self::U16),
            3 => Some(Self::Insets),
            4 => Some(Self::Alignment),
            5 => Some(Self::Edges),
            6 => Some(Self::Color),
            7 => Some(Self::BorderStyle),
            8 => Some(Self::Glyphs),
            9 => Some(Self::TextAttributes),
            10 => Some(Self::Style),
            11 => Some(Self::LayoutMode),
            12 => Some(Self::Dimension),
            13 => Some(Self::F32),
            14 => Some(Self::Display),
            15 => Some(Self::Direction),
            16 => Some(Self::FlexDirection),
            17 => Some(Self::FlexWrap),
            18 => Some(Self::Position),
            19 => Some(Self::AlignmentMode),
            20 => Some(Self::GridAutoFlow),
            21 => Some(Self::InsetsF32),
            22 => Some(Self::TrackList),
            23 => Some(Self::GridPlacement),
            _ => None,
        }
    }

    pub const fn code(self) -> u32 {
        self as u32
    }
}

#[derive(Clone, Copy, Debug)]
pub struct ValueEncodingDescriptor {
    pub value_kind: ValueKind,
    pub encoding: &'static str,
    pub min_words: usize,
    pub max_words: usize,
    pub metadata_words: usize,
    pub forms: &'static [ValueEncodingForm],
}

#[derive(Clone, Copy, Debug)]
pub struct ValueEncodingForm {
    pub name: &'static str,
    pub word_count: usize,
    pub tags: &'static [u32],
    pub names: &'static [&'static str],
    pub values: &'static [u32],
    pub mask: Option<u32>,
    pub max_value: Option<u32>,
}

pub const VALUE_ENCODING_DESCRIPTORS: &[ValueEncodingDescriptor] = &[
    ValueEncodingDescriptor {
        value_kind: ValueKind::U16,
        encoding: "u16",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "u16",
            word_count: 1,
            tags: &[],
            names: &[],
            values: &[],
            mask: None,
            max_value: Some(65535),
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Insets,
        encoding: "u16x4",
        min_words: 4,
        max_words: 4,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "u16x4",
            word_count: 4,
            tags: &[],
            names: &[],
            values: &[],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Alignment,
        encoding: "axis_x2",
        min_words: 2,
        max_words: 2,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "axis_pair",
            word_count: 2,
            tags: &[],
            names: &[],
            values: &[0, 1, 2, 3, 4],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Edges,
        encoding: "bool_x4",
        min_words: 4,
        max_words: 4,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "bool_x4",
            word_count: 4,
            tags: &[],
            names: &[],
            values: &[0, 1],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Color,
        encoding: "ansi_or_rgb_v1",
        min_words: 1,
        max_words: 4,
        metadata_words: 0,
        forms: &[
            ValueEncodingForm {
                name: "ansi",
                word_count: 1,
                tags: &[],
                names: &[],
                values: &[],
                mask: None,
                max_value: Some(255),
            },
            ValueEncodingForm {
                name: "rgb",
                word_count: 4,
                tags: &[2147483649],
                names: &[],
                values: &[],
                mask: None,
                max_value: None,
            },
        ],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::BorderStyle,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "border",
            word_count: 1,
            tags: &[],
            names: &["plain", "rounded", "double"],
            values: &[0, 1, 2],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Glyphs,
        encoding: "metadata_pairs_x8",
        min_words: 16,
        max_words: 16,
        metadata_words: 16,
        forms: &[ValueEncodingForm {
            name: "metadata_pairs_x8",
            word_count: 16,
            tags: &[],
            names: &[],
            values: &[],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::TextAttributes,
        encoding: "set_or_clear_bits_v1",
        min_words: 1,
        max_words: 2,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "set_or_clear",
            word_count: 2,
            tags: &[],
            names: &[],
            values: &[],
            mask: Some(63),
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Style,
        encoding: "direct_or_themed_style_v1",
        min_words: 9,
        max_words: 12,
        metadata_words: 2,
        forms: &[
            ValueEncodingForm {
                name: "direct",
                word_count: 9,
                tags: &[0, 1, 2],
                names: &[],
                values: &[],
                mask: Some(63),
                max_value: None,
            },
            ValueEncodingForm {
                name: "themed",
                word_count: 12,
                tags: &[0, 1, 2],
                names: &[],
                values: &[],
                mask: Some(63),
                max_value: None,
            },
        ],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::LayoutMode,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "layout",
            word_count: 1,
            tags: &[],
            names: &["box", "row", "column", "grid"],
            values: &[0, 1, 2, 3],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Dimension,
        encoding: "dimension_v1",
        min_words: 1,
        max_words: 2,
        metadata_words: 0,
        forms: &[
            ValueEncodingForm {
                name: "fit",
                word_count: 1,
                tags: &[0],
                names: &[],
                values: &[0],
                mask: None,
                max_value: None,
            },
            ValueEncodingForm {
                name: "fill",
                word_count: 1,
                tags: &[1],
                names: &[],
                values: &[1],
                mask: None,
                max_value: None,
            },
            ValueEncodingForm {
                name: "auto",
                word_count: 1,
                tags: &[2],
                names: &[],
                values: &[2],
                mask: None,
                max_value: None,
            },
            ValueEncodingForm {
                name: "length",
                word_count: 2,
                tags: &[3],
                names: &[],
                values: &[],
                mask: None,
                max_value: None,
            },
            ValueEncodingForm {
                name: "percent",
                word_count: 2,
                tags: &[4],
                names: &[],
                values: &[],
                mask: None,
                max_value: None,
            },
        ],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::F32,
        encoding: "f32_bits_v1",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "scalar",
            word_count: 1,
            tags: &[],
            names: &[],
            values: &[],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Display,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "display",
            word_count: 1,
            tags: &[],
            names: &["flex", "grid", "none"],
            values: &[0, 1, 2],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Direction,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "direction",
            word_count: 1,
            tags: &[],
            names: &["ltr", "rtl"],
            values: &[0, 1],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::FlexDirection,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "flex_direction",
            word_count: 1,
            tags: &[],
            names: &["row", "column", "rowReverse", "columnReverse"],
            values: &[0, 1, 2, 3],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::FlexWrap,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "flex_wrap",
            word_count: 1,
            tags: &[],
            names: &["nowrap", "wrap", "wrapReverse"],
            values: &[0, 1, 2],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::Position,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "position",
            word_count: 1,
            tags: &[],
            names: &["relative", "absolute"],
            values: &[0, 1],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::AlignmentMode,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "alignment_mode",
            word_count: 1,
            tags: &[],
            names: &[
                "start",
                "end",
                "center",
                "stretch",
                "baseline",
                "spaceBetween",
                "spaceEvenly",
                "spaceAround",
            ],
            values: &[0, 1, 2, 3, 4, 5, 6, 7],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::GridAutoFlow,
        encoding: "u32_enum",
        min_words: 1,
        max_words: 1,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "grid_auto_flow",
            word_count: 1,
            tags: &[],
            names: &["row", "column", "rowDense", "columnDense"],
            values: &[0, 1, 2, 3],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::InsetsF32,
        encoding: "dimension_x4_v1",
        min_words: 8,
        max_words: 8,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "dimension_x4",
            word_count: 8,
            tags: &[2, 3, 4],
            names: &[],
            values: &[],
            mask: None,
            max_value: None,
        }],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::TrackList,
        encoding: "track_list_v1",
        min_words: 1,
        max_words: 321,
        metadata_words: 0,
        forms: &[
            ValueEncodingForm {
                name: "tracks",
                word_count: 1,
                tags: &[0, 1, 2, 3, 4, 5, 6],
                names: &[],
                values: &[],
                mask: None,
                max_value: None,
            },
            ValueEncodingForm {
                name: "minmax_min",
                word_count: 1,
                tags: &[0, 1, 2, 3, 4],
                names: &[],
                values: &[],
                mask: None,
                max_value: None,
            },
            ValueEncodingForm {
                name: "minmax_max",
                word_count: 1,
                tags: &[0, 1, 2, 3, 4, 5],
                names: &[],
                values: &[],
                mask: None,
                max_value: None,
            },
        ],
    },
    ValueEncodingDescriptor {
        value_kind: ValueKind::GridPlacement,
        encoding: "grid_placement_v1",
        min_words: 4,
        max_words: 4,
        metadata_words: 0,
        forms: &[ValueEncodingForm {
            name: "placement",
            word_count: 4,
            tags: &[0, 1, 2],
            names: &[],
            values: &[],
            mask: None,
            max_value: None,
        }],
    },
];

pub fn value_encoding(value_kind: ValueKind) -> &'static ValueEncodingDescriptor {
    VALUE_ENCODING_DESCRIPTORS
        .iter()
        .find(|descriptor| descriptor.value_kind as u32 == value_kind as u32)
        .expect("validated value encoding descriptor")
}

pub fn value_encoding_form(value_kind: ValueKind, name: &str) -> &'static ValueEncodingForm {
    value_encoding(value_kind)
        .forms
        .iter()
        .find(|form| form.name == name)
        .expect("validated value encoding form")
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Effect {
    Presentation = 0,
    ContentProjection = 1,
    LayoutInput = 2,
    InteractionRuntime = 3,
    HostEnvironmentDependent = 4,
    StructureGuard = 5,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct EffectMask(pub u32);

impl EffectMask {
    pub const NONE: Self = Self(0);
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
}

pub const EFFECT_PRESENTATION: EffectMask = EffectMask(1 << 0);
pub const EFFECT_CONTENT_PROJECTION: EffectMask = EffectMask(1 << 1);
pub const EFFECT_LAYOUT_INPUT: EffectMask = EffectMask(1 << 2);
pub const EFFECT_INTERACTION_RUNTIME: EffectMask = EffectMask(1 << 3);
pub const EFFECT_HOST_ENVIRONMENT_DEPENDENT: EffectMask = EffectMask(1 << 4);
pub const EFFECT_STRUCTURE_GUARD: EffectMask = EffectMask(1 << 5);

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UiSection {
    Structure = 1,
    State = 2,
    ContentControl = 3,
    Events = 4,
    ContentDescriptor = 5,
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UiOpcode {
    CreateNode = 0x01,
    CreateRoot = 0x02,
    InsertBefore = 0x03,
    Detach = 0x04,
    RetireSubtree = 0x05,
    AttachPort = 0x06,
    AttachControl = 0x07,
    CreateControl = 0x08,
    DisposeControl = 0x09,
    HistoryAction = 0x0a,
    RetireRoot = 0x0b,
    SetDeclared = 0x10,
    ResetDeclared = 0x11,
    SetOverride = 0x12,
    ClearOverride = 0x13,
    SetHidden = 0x14,
    SetStyleState = 0x15,
    ClearStyleState = 0x16,
    ControlCommand = 0x18,
    CreatePort = 0x20,
    CreateConnector = 0x21,
    SelectConnector = 0x22,
    DisposeConnector = 0x23,
    DisposePort = 0x24,
    SetLiteralFunnel = 0x25,
    SetSubscriptions = 0x30,
    ReplaceLiteral = 0x40,
    ReplaceEditorContent = 0x41,
}

#[derive(Clone, Copy, Debug)]
pub struct OpcodeDescriptor {
    pub opcode: UiOpcode,
    pub section: UiSection,
    pub name: &'static str,
    pub operands: &'static [&'static str],
}

pub const OPCODE_DESCRIPTORS: &[OpcodeDescriptor] = &[
    OpcodeDescriptor {
        opcode: UiOpcode::CreateNode,
        section: UiSection::Structure,
        name: "CreateNode",
        operands: &["local_ordinal", "host_kind"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::CreateRoot,
        section: UiSection::Structure,
        name: "CreateRoot",
        operands: &[
            "local_ordinal",
            "root_role",
            "owner_handle_or_null",
            "config_metadata",
        ],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::InsertBefore,
        section: UiSection::Structure,
        name: "InsertBefore",
        operands: &["parent_handle", "child_handle", "before_handle_or_null"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::Detach,
        section: UiSection::Structure,
        name: "Detach",
        operands: &["parent_handle", "child_handle"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::RetireSubtree,
        section: UiSection::Structure,
        name: "RetireSubtree",
        operands: &["root_handle"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::AttachPort,
        section: UiSection::Structure,
        name: "AttachPort",
        operands: &["node_handle", "port_handle_or_null"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::AttachControl,
        section: UiSection::Structure,
        name: "AttachControl",
        operands: &["node_handle", "control_handle_or_null"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::CreateControl,
        section: UiSection::Structure,
        name: "CreateControl",
        operands: &[
            "local_ordinal",
            "control_kind",
            "ownership_mode",
            "owner_handle_or_null",
            "config_metadata",
        ],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::DisposeControl,
        section: UiSection::Structure,
        name: "DisposeControl",
        operands: &["control_handle"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::HistoryAction,
        section: UiSection::Structure,
        name: "HistoryAction",
        operands: &["unit_root_handle", "action_id"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::RetireRoot,
        section: UiSection::Structure,
        name: "RetireRoot",
        operands: &["root_handle"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SetDeclared,
        section: UiSection::State,
        name: "SetDeclared",
        operands: &["node_handle", "property_id", "typed_value"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::ResetDeclared,
        section: UiSection::State,
        name: "ResetDeclared",
        operands: &["node_handle", "property_id"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SetOverride,
        section: UiSection::State,
        name: "SetOverride",
        operands: &["node_handle", "property_id", "typed_value"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::ClearOverride,
        section: UiSection::State,
        name: "ClearOverride",
        operands: &["node_handle", "property_id"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SetHidden,
        section: UiSection::State,
        name: "SetHidden",
        operands: &["node_handle", "boolean"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SetStyleState,
        section: UiSection::State,
        name: "SetStyleState",
        operands: &["node_handle", "layer", "key_metadata", "typed_value"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::ClearStyleState,
        section: UiSection::State,
        name: "ClearStyleState",
        operands: &["node_handle", "layer", "key_metadata"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::ControlCommand,
        section: UiSection::State,
        name: "ControlCommand",
        operands: &["control_handle", "command_id", "typed_operands"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::CreatePort,
        section: UiSection::ContentControl,
        name: "CreatePort",
        operands: &[
            "local_ordinal",
            "family",
            "ownership_mode",
            "owner_handle_or_null",
        ],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::CreateConnector,
        section: UiSection::ContentControl,
        name: "CreateConnector",
        operands: &[
            "local_ordinal",
            "source_index",
            "port_handle",
            "funnel_metadata",
            "ownership_mode",
        ],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SelectConnector,
        section: UiSection::ContentControl,
        name: "SelectConnector",
        operands: &["port_handle", "connector_handle_or_null"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::DisposeConnector,
        section: UiSection::ContentControl,
        name: "DisposeConnector",
        operands: &["connector_handle"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::DisposePort,
        section: UiSection::ContentControl,
        name: "DisposePort",
        operands: &["port_handle"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SetLiteralFunnel,
        section: UiSection::ContentControl,
        name: "SetLiteralFunnel",
        operands: &["port_handle", "funnel_metadata"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::SetSubscriptions,
        section: UiSection::Events,
        name: "SetSubscriptions",
        operands: &["node_handle", "mask_low", "mask_high"],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::ReplaceLiteral,
        section: UiSection::ContentDescriptor,
        name: "ReplaceLiteral",
        operands: &[
            "port_handle",
            "content_format",
            "content_bytes",
            "annotations_bytes",
        ],
    },
    OpcodeDescriptor {
        opcode: UiOpcode::ReplaceEditorContent,
        section: UiSection::ContentDescriptor,
        name: "ReplaceEditorContent",
        operands: &["control_handle", "content_bytes", "expected_edit_revision"],
    },
];

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PropertyId {
    Width = 0x0101,
    Height = 0x0102,
    Padding = 0x0103,
    MinWidth = 0x0104,
    MaxWidth = 0x0105,
    MinHeight = 0x0106,
    MaxHeight = 0x0107,
    Gap = 0x0108,
    Alignment = 0x0109,
    BorderEdges = 0x010a,
    Foreground = 0x0201,
    Background = 0x0202,
    BorderColor = 0x0203,
    BorderStyle = 0x0204,
    BorderGlyphs = 0x0205,
    TextAttributes = 0x0206,
    Style = 0x0207,
    Layout = 0x010b,
    Display = 0x010c,
    Direction = 0x010d,
    FlexDirection = 0x010e,
    FlexWrap = 0x010f,
    FlexGrow = 0x0110,
    FlexShrink = 0x0111,
    FlexBasis = 0x0112,
    Margin = 0x0113,
    AlignItems = 0x0114,
    AlignSelf = 0x0115,
    AlignContent = 0x0116,
    JustifyContent = 0x0117,
    JustifyItems = 0x0118,
    JustifySelf = 0x0119,
    ColumnGap = 0x011a,
    RowGap = 0x011b,
    GridTemplateColumns = 0x011c,
    GridTemplateRows = 0x011d,
    GridAutoColumns = 0x011e,
    GridAutoRows = 0x011f,
    GridAutoFlow = 0x0120,
    GridColumn = 0x0121,
    GridRow = 0x0122,
    Position = 0x0123,
    Inset = 0x0124,
}

impl PropertyId {
    pub const ALL: &[Self] = &[
        Self::Width,
        Self::Height,
        Self::Padding,
        Self::MinWidth,
        Self::MaxWidth,
        Self::MinHeight,
        Self::MaxHeight,
        Self::Gap,
        Self::Alignment,
        Self::BorderEdges,
        Self::Foreground,
        Self::Background,
        Self::BorderColor,
        Self::BorderStyle,
        Self::BorderGlyphs,
        Self::TextAttributes,
        Self::Style,
        Self::Layout,
        Self::Display,
        Self::Direction,
        Self::FlexDirection,
        Self::FlexWrap,
        Self::FlexGrow,
        Self::FlexShrink,
        Self::FlexBasis,
        Self::Margin,
        Self::AlignItems,
        Self::AlignSelf,
        Self::AlignContent,
        Self::JustifyContent,
        Self::JustifyItems,
        Self::JustifySelf,
        Self::ColumnGap,
        Self::RowGap,
        Self::GridTemplateColumns,
        Self::GridTemplateRows,
        Self::GridAutoColumns,
        Self::GridAutoRows,
        Self::GridAutoFlow,
        Self::GridColumn,
        Self::GridRow,
        Self::Position,
        Self::Inset,
    ];

    pub const fn from_raw(value: u32) -> Option<Self> {
        match value {
            0x0101 => Some(Self::Width),
            0x0102 => Some(Self::Height),
            0x0103 => Some(Self::Padding),
            0x0104 => Some(Self::MinWidth),
            0x0105 => Some(Self::MaxWidth),
            0x0106 => Some(Self::MinHeight),
            0x0107 => Some(Self::MaxHeight),
            0x0108 => Some(Self::Gap),
            0x0109 => Some(Self::Alignment),
            0x010a => Some(Self::BorderEdges),
            0x0201 => Some(Self::Foreground),
            0x0202 => Some(Self::Background),
            0x0203 => Some(Self::BorderColor),
            0x0204 => Some(Self::BorderStyle),
            0x0205 => Some(Self::BorderGlyphs),
            0x0206 => Some(Self::TextAttributes),
            0x0207 => Some(Self::Style),
            0x010b => Some(Self::Layout),
            0x010c => Some(Self::Display),
            0x010d => Some(Self::Direction),
            0x010e => Some(Self::FlexDirection),
            0x010f => Some(Self::FlexWrap),
            0x0110 => Some(Self::FlexGrow),
            0x0111 => Some(Self::FlexShrink),
            0x0112 => Some(Self::FlexBasis),
            0x0113 => Some(Self::Margin),
            0x0114 => Some(Self::AlignItems),
            0x0115 => Some(Self::AlignSelf),
            0x0116 => Some(Self::AlignContent),
            0x0117 => Some(Self::JustifyContent),
            0x0118 => Some(Self::JustifyItems),
            0x0119 => Some(Self::JustifySelf),
            0x011a => Some(Self::ColumnGap),
            0x011b => Some(Self::RowGap),
            0x011c => Some(Self::GridTemplateColumns),
            0x011d => Some(Self::GridTemplateRows),
            0x011e => Some(Self::GridAutoColumns),
            0x011f => Some(Self::GridAutoRows),
            0x0120 => Some(Self::GridAutoFlow),
            0x0121 => Some(Self::GridColumn),
            0x0122 => Some(Self::GridRow),
            0x0123 => Some(Self::Position),
            0x0124 => Some(Self::Inset),
            _ => None,
        }
    }

    pub const fn index(self) -> usize {
        match self {
            Self::Width => 0,
            Self::Height => 1,
            Self::Padding => 2,
            Self::MinWidth => 3,
            Self::MaxWidth => 4,
            Self::MinHeight => 5,
            Self::MaxHeight => 6,
            Self::Gap => 7,
            Self::Alignment => 8,
            Self::BorderEdges => 9,
            Self::Foreground => 10,
            Self::Background => 11,
            Self::BorderColor => 12,
            Self::BorderStyle => 13,
            Self::BorderGlyphs => 14,
            Self::TextAttributes => 15,
            Self::Style => 16,
            Self::Layout => 17,
            Self::Display => 18,
            Self::Direction => 19,
            Self::FlexDirection => 20,
            Self::FlexWrap => 21,
            Self::FlexGrow => 22,
            Self::FlexShrink => 23,
            Self::FlexBasis => 24,
            Self::Margin => 25,
            Self::AlignItems => 26,
            Self::AlignSelf => 27,
            Self::AlignContent => 28,
            Self::JustifyContent => 29,
            Self::JustifyItems => 30,
            Self::JustifySelf => 31,
            Self::ColumnGap => 32,
            Self::RowGap => 33,
            Self::GridTemplateColumns => 34,
            Self::GridTemplateRows => 35,
            Self::GridAutoColumns => 36,
            Self::GridAutoRows => 37,
            Self::GridAutoFlow => 38,
            Self::GridColumn => 39,
            Self::GridRow => 40,
            Self::Position => 41,
            Self::Inset => 42,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PropertyDescriptor {
    pub id: PropertyId,
    pub name: &'static str,
    pub domain: &'static str,
    pub value_kind: ValueKind,
    pub legal_kinds: &'static [HostKind],
    pub normalizer: &'static str,
    pub default: &'static str,
    pub reset: &'static str,
    pub override_behavior: &'static str,
    pub inheritance: &'static str,
    pub effects: EffectMask,
    pub realization: &'static str,
    pub nullable: bool,
    pub clearable: bool,
    pub allowed_values: &'static [&'static str],
}

pub const PROPERTY_DESCRIPTORS: &[PropertyDescriptor] = &[
    PropertyDescriptor {
        id: PropertyId::Width,
        name: "width",
        domain: "geometry",
        value_kind: ValueKind::Dimension,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "dimension",
        default: "unset",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 2))
            .union(EffectMask(1 << 1)),
        realization: "layout",
        nullable: false,
        clearable: true,
        allowed_values: &["fit", "fill", "length", "percent"],
    },
    PropertyDescriptor {
        id: PropertyId::Height,
        name: "height",
        domain: "geometry",
        value_kind: ValueKind::Dimension,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "dimension",
        default: "unset",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "layout",
        nullable: false,
        clearable: true,
        allowed_values: &["fit", "fill", "length", "percent"],
    },
    PropertyDescriptor {
        id: PropertyId::Padding,
        name: "padding",
        domain: "geometry",
        value_kind: ValueKind::Insets,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "insets",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 2))
            .union(EffectMask(1 << 1)),
        realization: "layout",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::MinWidth,
        name: "minWidth",
        domain: "geometry",
        value_kind: ValueKind::U16,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "u16",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 2))
            .union(EffectMask(1 << 1)),
        realization: "layout",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::MaxWidth,
        name: "maxWidth",
        domain: "geometry",
        value_kind: ValueKind::U16,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "u16",
        default: "unbounded",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 2))
            .union(EffectMask(1 << 1)),
        realization: "layout",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::MinHeight,
        name: "minHeight",
        domain: "geometry",
        value_kind: ValueKind::U16,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "u16",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "layout",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::MaxHeight,
        name: "maxHeight",
        domain: "geometry",
        value_kind: ValueKind::U16,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "u16",
        default: "unbounded",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "layout",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Gap,
        name: "gap",
        domain: "geometry",
        value_kind: ValueKind::U16,
        legal_kinds: &[HostKind::Box, HostKind::Scroll, HostKind::Animation],
        normalizer: "u16",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "layout",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Alignment,
        name: "alignment",
        domain: "geometry",
        value_kind: ValueKind::Alignment,
        legal_kinds: &[HostKind::Box, HostKind::Scroll, HostKind::Animation],
        normalizer: "alignment",
        default: "unset",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "layout",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::BorderEdges,
        name: "borderEdges",
        domain: "geometry",
        value_kind: ValueKind::Edges,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "border_edges",
        default: "unset",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 2))
            .union(EffectMask(1 << 1)),
        realization: "layout",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Foreground,
        name: "foreground",
        domain: "presentation",
        value_kind: ValueKind::Color,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "color",
        default: "inherit",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "theme",
        effects: EffectMask::NONE.union(EffectMask(1 << 0)),
        realization: "paint",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Background,
        name: "background",
        domain: "presentation",
        value_kind: ValueKind::Color,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "color",
        default: "inherit",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "theme",
        effects: EffectMask::NONE.union(EffectMask(1 << 0)),
        realization: "paint",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::BorderColor,
        name: "borderColor",
        domain: "presentation",
        value_kind: ValueKind::Color,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "color",
        default: "inherit",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "theme",
        effects: EffectMask::NONE.union(EffectMask(1 << 0)),
        realization: "paint",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::BorderStyle,
        name: "borderStyle",
        domain: "presentation",
        value_kind: ValueKind::BorderStyle,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "border_style",
        default: "plain",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 0))
            .union(EffectMask(1 << 2)),
        realization: "paint",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::BorderGlyphs,
        name: "borderGlyphs",
        domain: "presentation",
        value_kind: ValueKind::Glyphs,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "glyphs",
        default: "style_default",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 0)),
        realization: "paint",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::TextAttributes,
        name: "textAttributes",
        domain: "presentation",
        value_kind: ValueKind::TextAttributes,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "text_attributes",
        default: "inherit",
        reset: "unset",
        override_behavior: "sparse",
        inheritance: "theme",
        effects: EffectMask::NONE.union(EffectMask(1 << 0)),
        realization: "paint",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Style,
        name: "style",
        domain: "presentation",
        value_kind: ValueKind::Style,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "style",
        default: "inherit",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "theme",
        effects: EffectMask::NONE
            .union(EffectMask(1 << 0))
            .union(EffectMask(1 << 4)),
        realization: "paint",
        nullable: true,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Layout,
        name: "layout",
        domain: "geometry",
        value_kind: ValueKind::LayoutMode,
        legal_kinds: &[HostKind::Box],
        normalizer: "layout",
        default: "box",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "layout",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Display,
        name: "display",
        domain: "geometry",
        value_kind: ValueKind::Display,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "display",
        default: "flex",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_display",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Direction,
        name: "direction",
        domain: "geometry",
        value_kind: ValueKind::Direction,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "direction",
        default: "ltr",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_direction",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::FlexDirection,
        name: "flexDirection",
        domain: "geometry",
        value_kind: ValueKind::FlexDirection,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "flex_direction",
        default: "row",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_flex_direction",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::FlexWrap,
        name: "flexWrap",
        domain: "geometry",
        value_kind: ValueKind::FlexWrap,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "flex_wrap",
        default: "nowrap",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_flex_wrap",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::FlexGrow,
        name: "flexGrow",
        domain: "geometry",
        value_kind: ValueKind::F32,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "float",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_flex_grow",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::FlexShrink,
        name: "flexShrink",
        domain: "geometry",
        value_kind: ValueKind::F32,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "float",
        default: "one",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_flex_shrink",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::FlexBasis,
        name: "flexBasis",
        domain: "geometry",
        value_kind: ValueKind::Dimension,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "dimension",
        default: "auto",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_flex_basis",
        nullable: false,
        clearable: true,
        allowed_values: &["auto", "length", "percent"],
    },
    PropertyDescriptor {
        id: PropertyId::Margin,
        name: "margin",
        domain: "geometry",
        value_kind: ValueKind::InsetsF32,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "dimensions",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_margin",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::AlignItems,
        name: "alignItems",
        domain: "geometry",
        value_kind: ValueKind::AlignmentMode,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "alignment_mode",
        default: "stretch",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_align_items",
        nullable: false,
        clearable: true,
        allowed_values: &["start", "end", "center", "stretch", "baseline"],
    },
    PropertyDescriptor {
        id: PropertyId::AlignSelf,
        name: "alignSelf",
        domain: "geometry",
        value_kind: ValueKind::AlignmentMode,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "alignment_mode",
        default: "auto",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_align_self",
        nullable: false,
        clearable: true,
        allowed_values: &["start", "end", "center", "stretch", "baseline"],
    },
    PropertyDescriptor {
        id: PropertyId::AlignContent,
        name: "alignContent",
        domain: "geometry",
        value_kind: ValueKind::AlignmentMode,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "alignment_mode",
        default: "stretch",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_align_content",
        nullable: false,
        clearable: true,
        allowed_values: &[
            "start",
            "end",
            "center",
            "stretch",
            "spaceBetween",
            "spaceEvenly",
            "spaceAround",
        ],
    },
    PropertyDescriptor {
        id: PropertyId::JustifyContent,
        name: "justifyContent",
        domain: "geometry",
        value_kind: ValueKind::AlignmentMode,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "alignment_mode",
        default: "start",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_justify_content",
        nullable: false,
        clearable: true,
        allowed_values: &[
            "start",
            "end",
            "center",
            "stretch",
            "spaceBetween",
            "spaceEvenly",
            "spaceAround",
        ],
    },
    PropertyDescriptor {
        id: PropertyId::JustifyItems,
        name: "justifyItems",
        domain: "geometry",
        value_kind: ValueKind::AlignmentMode,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "alignment_mode",
        default: "stretch",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_justify_items",
        nullable: false,
        clearable: true,
        allowed_values: &["start", "end", "center", "stretch", "baseline"],
    },
    PropertyDescriptor {
        id: PropertyId::JustifySelf,
        name: "justifySelf",
        domain: "geometry",
        value_kind: ValueKind::AlignmentMode,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "alignment_mode",
        default: "auto",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_justify_self",
        nullable: false,
        clearable: true,
        allowed_values: &["start", "end", "center", "stretch", "baseline"],
    },
    PropertyDescriptor {
        id: PropertyId::ColumnGap,
        name: "columnGap",
        domain: "geometry",
        value_kind: ValueKind::Dimension,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "nonnegative_dimension",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_column_gap",
        nullable: false,
        clearable: true,
        allowed_values: &["length", "percent"],
    },
    PropertyDescriptor {
        id: PropertyId::RowGap,
        name: "rowGap",
        domain: "geometry",
        value_kind: ValueKind::Dimension,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "nonnegative_dimension",
        default: "zero",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_row_gap",
        nullable: false,
        clearable: true,
        allowed_values: &["length", "percent"],
    },
    PropertyDescriptor {
        id: PropertyId::GridTemplateColumns,
        name: "gridTemplateColumns",
        domain: "geometry",
        value_kind: ValueKind::TrackList,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "track_list",
        default: "empty",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_template_columns",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::GridTemplateRows,
        name: "gridTemplateRows",
        domain: "geometry",
        value_kind: ValueKind::TrackList,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "track_list",
        default: "empty",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_template_rows",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::GridAutoColumns,
        name: "gridAutoColumns",
        domain: "geometry",
        value_kind: ValueKind::TrackList,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "track_list",
        default: "empty",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_auto_columns",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::GridAutoRows,
        name: "gridAutoRows",
        domain: "geometry",
        value_kind: ValueKind::TrackList,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "track_list",
        default: "empty",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_auto_rows",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::GridAutoFlow,
        name: "gridAutoFlow",
        domain: "geometry",
        value_kind: ValueKind::GridAutoFlow,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "grid_auto_flow",
        default: "row",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_auto_flow",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::GridColumn,
        name: "gridColumn",
        domain: "geometry",
        value_kind: ValueKind::GridPlacement,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "grid_placement",
        default: "auto",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_column",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::GridRow,
        name: "gridRow",
        domain: "geometry",
        value_kind: ValueKind::GridPlacement,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "grid_placement",
        default: "auto",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_grid_row",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Position,
        name: "position",
        domain: "geometry",
        value_kind: ValueKind::Position,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "position",
        default: "relative",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_position",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
    PropertyDescriptor {
        id: PropertyId::Inset,
        name: "inset",
        domain: "geometry",
        value_kind: ValueKind::InsetsF32,
        legal_kinds: &[
            HostKind::Box,
            HostKind::ContentHost,
            HostKind::Editor,
            HostKind::Scroll,
            HostKind::Animation,
        ],
        normalizer: "dimensions",
        default: "auto",
        reset: "unset",
        override_behavior: "explicit",
        inheritance: "none",
        effects: EffectMask::NONE.union(EffectMask(1 << 2)),
        realization: "taffy_inset",
        nullable: false,
        clearable: true,
        allowed_values: &[],
    },
];

pub const PROPERTY_COUNT: usize = PROPERTY_DESCRIPTORS.len();

pub const fn property_descriptor(id: PropertyId) -> &'static PropertyDescriptor {
    &PROPERTY_DESCRIPTORS[id.index()]
}
