[package]
name = "iyon-tui"
license = "MIT"
version.workspace = true
edition.workspace = true

[features]
test-util = []
native-host = []
native-shared-memory = []
perf-counters = []
perf-timing = []

[[bin]]
name = "tui_perf"
path = "src/bin/tui_perf.rs"
required-features = ["perf-counters"]

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
termwiz.workspace = true
unicode-segmentation.workspace = true
unicode-linebreak.workspace = true
tokio.workspace = true
pulldown-cmark.workspace = true

[dev-dependencies]
vt100.workspace = true
proptest.workspace = true
insta.workspace = true
trybuild.workspace = true
