[package]
name = "tui-abi-gen"
license = "MIT"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "tui-abi-gen"
path = "src/main.rs"

[dependencies]
blake3.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
prettyplease.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
syn.workspace = true
thiserror.workspace = true
toml.workspace = true
toml_edit.workspace = true

[lints]
workspace = true
