[package]
name = "iyon-api"
license = "MIT"
version.workspace = true
edition.workspace = true

[dependencies]
futures-core.workspace = true
futures-util.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
async-stream = "0.3.6"
base64.workspace = true
