[package]
name = "iyon-core"
license = "MIT"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
iyon-api.workspace = true
thiserror = "2.0.18"
which.workspace = true
similar.workspace = true
tempfile.workspace = true
